### ISSUE TITLE
How to import this library?

### ISSUE THREAD

**Issue by ally9335** [karlseguin/zul#3]
Let's say, I have a project. How would I import this library into it?  There's no mention of this. The examples in the readme are about the content of the library.

**Comment by karlseguin** [comment]
I'll update the readme, but it's like any other Zig library. Plus, the way this library is structured, you can always just copy and paste a file into your own project, since each "part" is a standalone file.

You start with a `build.zig.zon:
```zig
.{
  .name = "my-app",
  .paths = .{""},
  .version = "0.0.0",
  .dependencies = .{
    .zul = .{
.url = "https://github.com/karlseguin/zul/archive/7779642127b560a04075da96d9d07703847923cb.tar.gz",
			.hash = "12203d26bd4179e9072949037a2a99a12c88909c27f2465f230beec7b1a6b1db8688"
    },
  },
}
```

The commit is the latest commit. The hash you can get from running:

```bash
zig fetch https://github.com/karlseguin/zul/archive/7779642127b560a04075da96d9d07703847923cb.tar.gz
```

Then, in your build.zig, you should have a call to `b.addExecutable` which returns a value, something like:

```zig
const exe = b.addExecutable(.{
    .name = "my-lib",
    .root_source_file = b.path("src/main.zig"),
    .target = target,
    .optimize = optimize,
});
```

You would add this line after:

```zig
exe.root_module.addImport("zul", b.dependency("zul", .{}).module("zul"));
```

which would then allow you to import zul in your code:

```zig
const zul = @import("zul");
```

**Comment by ally9335** [comment]
Thx
